config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup',to: 'users#new'
  get '/login',to: 'sessions#new'
  post '/login',to: 'sessions#create'
  get '/auth/:provider/callback',to:'sessions#twitter'
  delete '/logout',to: 'sessions#destroy'
  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'
  resources :users
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :microposts do
    resources :likes, only:[:create,:destroy]
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :micropost, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, micropost_id: params[:micropost_id])
    @likes = Like.where(micropost_id: params[:micropost_id])
    @micropost = Micropost.find(params[:micropost_id])
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, micropost_id: params[:micropost_id])
    like.destroy
    @likes = Like.where(micropost_id: params[:micropost_id])
    @micropost = Micropost.find(params[:micropost_id])
  end
end

app/views/likes/_like.html.erb
<% if micropost.like_user(current_user.id) %>
  <%= button_to micropost_like_path(likes, micropost_id: micropost.id), method: :delete, id: "like-button", remote: true do %>
    <%= image_tag("icon_red_heart.png") %>
    <span>
      <%= micropost.likes_count %>
    </span>
  <% end %>
<% else %>
  <%= button_to micropost_likes_path(micropost),id: "like-button", remote: true do %>
    <%= image_tag("icon_heart.png") %>
    <span>
      <%= micropost.likes_count %>
    </span>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$("#ajax").html("<p><%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes, like: @like}) %></p>");

app/views/likes/destroy.js.erb
$("#ajax").html("<p><%= j(render partial: 'like', locals: { micropost: @micropost, likes: @likes }) %></p>");