config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup',to: 'users#new'
  get '/login',to: 'sessions#new'
  post '/login',to: 'sessions#create'
  get '/auth/:provider/callback',to:'sessions#twitter'
  delete '/logout',to: 'sessions#destroy'
  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'
  resources :users
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :microposts do
    resources :likes, only:[:create,:destroy]
  end
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX ,:message => 'メールアドレスを入力してください'}
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @contact = Contact.new(params[:contact])
    ContactMailer.received_email(@contact).deliver

    render :action => 'thanks'
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>

<%= form_for @contact, :url => contact_thanks_path do |f| %>
  <table>
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @contact.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @contact.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@contact.message) %>
      </td>
    </tr>
  </table>
 <%= f.submit '送信' %>
<% end %>

app/views/contacts/index.html.erb
<%= form_for @contact,:url => contact_confirm_path do |f| %>
  <div class="page-header">
    <h1>お問い合わせ</h1>
  </div>

  <% if @contact.errors.any? %>
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @contact.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>

  <table>
    <tr>
      <th>名前（必須）</th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>メールアドレス（必須）</th>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td><%= f.text_area :message %></td>
    </tr>
  </table>
  <%= f.submit '確認' %>
<% end %>

app/views/contacts/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>