config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/signup',to: 'users#new'
  get '/login',to: 'sessions#new'
  post '/login',to: 'sessions#create'
  get '/auth/:provider/callback',to:'sessions#twitter'
  delete '/logout',to: 'sessions#destroy'
  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'
  resources :users
  resources :password_resets, only:[:new,:create,:edit,:update]
  resources :microposts do
    resources :likes, only:[:create,:destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <ul>利用規約</ul>
    <ul>プライバシーポリシー</ul>
  </small>
  <nav>
    <ul>
      <li><%=link_to "お問い合わせ","#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%=link_to "Jeans.Co",root_path,id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Jeans.Coとは",'#' %></li>
        <li><%=link_to "投稿一覧",microposts_path %></li>
        <% if logged_in? %>
        <li><%=link_to "投稿する",new_micropost_path %></li>
        <li><%=link_to "マイページ",current_user %></li>
        <li><%=link_to "ログアウト",logout_path,method: :delete %>
        <% else %>
        <li><%=link_to "会員登録",signup_path %></li>
        <li><%=link_to "ログイン",login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>

    
  </body>
</html>